language: python

python:
    - 2.7

env:
    matrix:
        - SYSTEM_PACKAGES=false
        - SYSTEM_PACKAGES=true

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install python-twisted python-qt4 lua5.2-dev zlib1g-dev python-imaging
    - pip install qt4reactor psutil requests jsonschema strict-rfc3339 xvfbwrapper pytest funcparserlib
    - "if [[ $SYSTEM_PACKAGES == 'false' ]]; then pip install -UI Pillow twisted service_identity lupa; fi"

install:
    - python setup.py install

script:
    - py.test --doctest-modules splash
